/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;

/**
 *
 * @author chris
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_analizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultadoSintax = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_analizar.setText("Analizar");
        btn_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarActionPerformed(evt);
            }
        });

        Resultado.setColumns(20);
        Resultado.setRows(5);
        jScrollPane2.setViewportView(Resultado);

        ResultadoSintax.setColumns(20);
        ResultadoSintax.setRows(5);
        jScrollPane1.setViewportView(ResultadoSintax);

        jLabel1.setText("ANALIZADOR LEXICO");

        jLabel2.setText("ANALIZADOR SINTACTICO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btn_analizar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(btn_analizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarActionPerformed
        JFileChooser escoger = new JFileChooser();
        escoger.showOpenDialog(null);
        try {
   	Reader lector2 = new BufferedReader(new FileReader(escoger.getSelectedFile()));
   	Sintax s = new Sintax(new LexerCup(lector2));
   	
   	try {
           s.parse();
          ResultadoSintax.setText("Analisis realizado correctamente");
            } catch (Exception ex) {
           Symbol sym = s.getS();
           ResultadoSintax.setText("Error de sintaxis. Linea: " + (sym.right + 1) + " Columna: " + (sym.left + 1) + ", Texto: \"" + sym.value + "\"");
          }
   	
   	
   	}catch (FileNotFoundException e) {
   		System.out.println("ERROR");
   		// TODO Auto-generated catch block
      		e.printStackTrace();
   	
   	}
        
        
        
        int cont = 1;
        
        try {
            Reader lectura = new BufferedReader(new FileReader(escoger.getSelectedFile()));
            Lexer lexicos = new Lexer(lectura);
            String result = "";
            while (true) {
                Tokens tokens = lexicos.yylex();
                if (tokens == null) {
                    result += "Final";
                    Resultado.setText(result);
                    return;
                }
                switch (tokens) {
                    case Linea:
                        cont++;
                        result += "LINEA " + cont + "\n";
                        break;
                    case Comillas:
                        result += " <Comillas>\t\t" + lexicos.lexeme + "\n";
                        break;
                    case Cadena:
                        result += " <Tipo de dato>\t" + lexicos.lexeme + "\n";
                        break;
                    case T_dato:
                        result += " <Tipo de dato>\t" + lexicos.lexeme + "\n";
                        break;
                    case If:
                        result += " <Reservada if>\t" + lexicos.lexeme + "\n";
                        break;
                    case Else:
                        result += " <Reservada else>\t" + lexicos.lexeme + "\n";
                        break;
                    case Do:
                        result += " <Reservada do>\t" + lexicos.lexeme + "\n";
                        break;
                    case While:
                        result += " <Reservada while>\t" + lexicos.lexeme + "\n";
                        break;
                    case For:
                        result += " <Reservada while>\t" + lexicos.lexeme + "\n";
                        break;
                    case Igual:
                        result += " <Operador igual>\t" + lexicos.lexeme + "\n";
                        break;
                    case Suma:
                        result += " <Operador suma>\t" + lexicos.lexeme + "\n";
                        break;
                    case Resta:
                        result += " <Operador resta>\t" + lexicos.lexeme + "\n";
                        break;
                    case Multiplicacion:
                        result += " <Operador multiplicacion>\t" + lexicos.lexeme + "\n";
                        break;
                    case Division:
                        result += " <Operador division>\t" + lexicos.lexeme + "\n";
                        break;
                    case Op_logico:
                        result += " <Operador logico>\t" + lexicos.lexeme + "\n";
                        break;
                    case Op_incremento:
                        result += " <Operador incremento>\t" + lexicos.lexeme + "\n";
                        break;
                    case Op_relacional:
                        result += " <Operador relacional>\t" + lexicos.lexeme + "\n";
                        break;
                    case Op_atribucion:
                        result += " <Operador atribucion>\t" + lexicos.lexeme + "\n";
                        break;
                    case Op_booleano:
                        result += " <Operador booleano>\t" + lexicos.lexeme + "\n";
                        break;
                    case Parentesis_a:
                        result += " <Parentesis de apertura>\t" + lexicos.lexeme + "\n";
                        break;
                    case Parentesis_c:
                        result += " <Parentesis de cierre>\t" + lexicos.lexeme + "\n";
                        break;
                    case Llave_a:
                        result += " <Llave de apertura>\t" + lexicos.lexeme + "\n";
                        break;
                    case Llave_c:
                        result += " <Llave de cierre>\t" + lexicos.lexeme + "\n";
                        break;
                    case Corchete_a:
                        result += " <Corchete de apertura>\t" + lexicos.lexeme + "\n";
                        break;
                    case Corchete_c:
                        result += " <Corchete de cierre>\t" + lexicos.lexeme + "\n";
                        break;
                    case Main:
                        result += " <Reservada main>\t" + lexicos.lexeme + "\n";
                        break;
                    case P_coma:
                        result += " <Punto y coma>\t" + lexicos.lexeme + "\n";
                        break;
                    case Identificador:
                        result += " <Identificador>\t\t" + lexicos.lexeme + "\n";
                        break;
                    case Numero:
                        result += " <Numero>\t\t" + lexicos.lexeme + "\n";
                        break;
                    case ERROR:
                        result += " <Simbolo no definido>\n";
                        break;
                    default:
                        result += " < " + lexicos.lexeme + " >\n";
                        break;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_analizarActionPerformed
                                

    public void LexerFile() throws IOException {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Resultado;
    private javax.swing.JTextArea ResultadoSintax;
    private javax.swing.JButton btn_analizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
